services:
    app:
        build: .
        ports:
            - "8080:8080"
            - "51212:51212"
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy

        environment:
            DATABASE_URL: postgresql://postgres:password@db:5432/bank_management?schema=public
            ENVIRONMENT: DEVELOPMENT
            JWT_SECRET: supersecret123
            REDIS_URL: redis://redis:6379
        command: sh -c "npx prisma db push && (npx prisma studio --browser none --port 51212 & npm run start)"
        networks:
            - bank_management
    db:
        image: postgres:18.0-alpine3.22
        container_name: bank_management_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: bank_management
        networks:
            - bank_management
        volumes:
            - bank_management_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d bank_management"]
            interval: 5s
            timeout: 5s
            retries: 5
    redis:
        image: redis:alpine
        container_name: bank_management_redis
        ports:
            - "6379:6379"
        networks:
            - bank_management
        volumes:
            - bank_management_redis_data:/data
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 5s
            timeout: 5s
            retries: 5
networks:
    bank_management:
        driver: bridge
volumes:
    bank_management_data:
    bank_management_redis_data:
